---
version: "3.0"

services:

# 
# postgresql
#

#
# nest
# 

#
# react
# 

# nginx
#
  nginx:
    build:
      context: ./srcs/nginx
    container_name: nginx
    image: nginx 
    restart: always
    volumes:
      - react:/var/www/react
    networks:
      - react
    ports:
      - '443:443'

volumes:
  postgresql:
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_DEVICE}/postgresql
  react:
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_DEVICE}/dist

networks:
  react:
...
