---
version: "3.0"
services:

  db:
    image: postgres:14-alpine3.15
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./srcs/postgres/.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    networks:
      - postgres
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres:

networks:
  postgres:
...
