---
version: "3.0"
services:

  postgres:
    image: postgres:14-alpine3.15
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./srcs/postgres/.env

  adminer:
    image: adminer
    networks:
      - postgres
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/postgres
  front:
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/dist

volumes:
  postgres:

networks:
  postgres:
...
